name: Build and Deploy to GH Pages

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: latest
    steps:
      # We need to setup our timezone so that git commits are correctly timestamped. This otherwise interferes with post update times.
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Berlin
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build static files
        run: hugo --minify
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./public"
  deploy:
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
